apiVersion: v1
data:
  mongodb.conf: |
    storage:
       wiredTiger:
         engineConfig:
           cacheSizeGB: 1
       dbPath: /data/db
       journal:
          enabled: true
    processManagement:
       fork: false
    net:
       bindIp: 0.0.0.0
       port: 27017
    setParameter:
       enableLocalhostAuthBypass: false
    replication:
      replSetName: dev-gcp-replica-set
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mongo-config
  namespace: rs-test
